### ISSUE TITLE
Datadog Extension layer is reported present when it is not, causing metric reporting to fail

### ISSUE THREAD

**Issue by mtentoni** [DataDog/datadog-lambda-python#102]
## Expected Behavior
When the Datadog Lambda Extension is not present in an AWS Lambda, `should_use_extension` will be false, and `lambda_metric` will use ThreadStats to report metrics.

## Actual Behavior
The code to check if the statsd agent is running [(is_extension_running)](https://github.com/DataDog/datadog-lambda-python/blob/master/datadog_lambda/extension.py#L11) returns true during an execution of a Lambda that does not have the Datadog Extension layer. This causes the StatsDWrapper to be used for metrics, which will fail to send to the agent as it is not actually running.

It looks like the reason for this is that when the Extension is not present, the check for `http://127.0.0.1:8124/lambda/hello` will result in a 4xx HTTP code (I believe a 403) which does not cause `requests.get` to raise an exception.

## Steps to Reproduce the Problem

  1. Deploy a Lambda based on the minimal example [here](https://docs.datadoghq.com/serverless/custom_metrics?tab=python), with version 26 of the Lambda Layer and no Extension Layer.
  2. Run an execution of the Lambda
  3. See warnings in the logs as described below. Metric will not have been reported.

Downgrading to layer version 21 fixes this.

## Specifications

  - Datadog Lambda Layer version: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Python37:26
  - Python version: 3.7
  
## Stacktrace
  
At execution start:
```
WARNING <snip> No agent or invalid configuration file found
```
At the point of metric reporting:
```
DEBUG <snip> Sending metric example.metric to Datadog via lambda layer
WARNING <snip> Error submitting packet: [Errno 111] Connection refused, dropping the packet and closing the socket
```

**Comment by DarcyRaynerDD** [comment]
Hi @mtentoni, thanks for the report. I've been trying to reproduce this on v26, but haven't had any luck. If you turn on debug logging by setting the `DD_LOG_LEVEL` env var to `DEBUG`, do you see any lines like 'Extension is not running' in your logs? I think the only way the extension check can receive a 403 is if something else is running on that port.

**Comment by DarcyRaynerDD** [comment]
The other thing to note is, the 'No agent or invalid configuration file found' warning actually comes from the extension itself, so I just want to double check it's not actually installed.

**Comment by mtentoni** [comment]
Just double checked - I still see the "No agent or invalid configuration file found" as the very first log message, and then later I still see the warning with "Error submitting packet...". I don't see anything like "Extension is not running". I already had `DD_LOG_LEVEL` set to debug, and I definitely only have one layer on my Lambda which is `arn:aws:lambda:us-east-1:464622532012:layer:Datadog-37:26`. I can look into if there's something I'm not aware of in my environment that would interfere, though I'm not sure what it would be

**Comment by tianchu** [comment]
@mtentoni is this issue still reproducible on the latest version (40) of the layer? I'm closing the issue for now, since we haven't heard similar reports from anyone else and there have been lots of changes and improvements over the past few months both in the Lambda library layer and the Lambda extension layer. But please reopen if the issue still persists on the latest version for you and please help provide some instructions for us to reproduce the issue, thank you!
