### ISSUE TITLE
Pinned setuptools version (setuptools==42.0.2) is too restrictive

### ISSUE THREAD

**Issue by zlalvani** [DataDog/datadog-lambda-python#104]
## Expected Behavior
Dependency versions are loose enough to be resolved in most cases

## Actual Behavior
Pinned dependency on `setuptools` is old and potentially too specific

## Steps to Reproduce the Problem

  1. `pip install -r requirements.txt` in a requirements file with both datadog-lambda and another dependency with a conflicting `setuptools` version. In this case, `wiremock`. 

## Specifications

  - Datadog Lambda Layer version: 2.26.0
  - Python version: 3.8.6
  
## Stacktrace
  
  ```
ERROR: Cannot install -r requirements-dev.txt (line 13) and -r requirements.txt (line 14) because these package versions have conflicting dependencies.

The conflict is caused by:
    datadog-lambda 2.26.0 depends on setuptools==42.0.2
    wiremock 2.1.3 depends on setuptools>=45.2.0  
```

**Comment by ryboe** [comment]
Yes, we're having issues with Ye Olde Setuptools too.

```
Collecting setuptools==42.0.2
  Downloading setuptools-42.0.2-py2.py3-none-any.whl (583 kB)
ERROR: Hashes are required in --require-hashes mode, but they are missing from some requirements. Here is a list of those requirements along with the hashes their downloaded archives actually had. Add lines like these to your requirements files to prevent tampering. (If you did not enable --require-hashes manually, note that it turns on automatically when any package has a hash.)
    setuptools==42.0.2 --hash=sha256:c8abd0f3574bc23afd2f6fd2c415ba7d9e097c8a99b845473b0d957ba1e2dac6
```

**Comment by sfirrin** [comment]
Hi @zlalvani and @ryboe, thanks for bringing this to our attention. As of https://github.com/DataDog/datadog-lambda-python/releases/tag/v32 we're now specifying the current latest version of setuptools or greater. If you're still running into issues please reopen and let us know.
