### ISSUE TITLE
Cannot add both datadog extension and datadog python layers

### ISSUE THREAD

**Issue by babyhuey** [DataDog/datadog-lambda-python#111]
## Expected Behavior
According to the [Datadog Lambda Extension (Preview)](https://docs.datadoghq.com/serverless/datadog_lambda_library/extension/) page, I have to add both `arn:aws:lambda:<AWS_REGION>:464622532012:layer:Datadog-Extension:5` and `arn:aws:lambda:<AWS_REGION>:464622532012:layer:Datadog-<RUNTIME>:<VERSION>` to the lambda. 

## Actual Behavior
When I try to add the Datadog-Extension layer, I get the following error; Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 281207280 bytes.

## Steps to Reproduce the Problem

  1. Follow instrumentation for serverless application on this page: https://docs.datadoghq.com/serverless/installation/python/?tab=serverlessframework
  1. Add second layer `arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:5` via console

## Specifications

  - Datadog Lambda Layer version: v27
  - Python version: 3.8

**Comment by DylanLovesCoffee** [comment]
Hey @babyhuey thanks for bringing this to our attention. It seems like you're hitting the Lambda [deployment size limit](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html). The combined size of the Datadog Lambda library and extension layers should not encompass the entirety of the 250mb unzipped limit, but we'll look into way of maintaining a minimal size. In the meantime, without trying to reduce the deployment size altogether, using the Datadog Forwarder may be a good option.

**Comment by babyhuey** [comment]
Oh my. Well, this is an entirely me issue then. I apologize. I will see if I can bring down my image size.

I'm still not seeing APM data, even with the forwarder, but that is another issue I will look into. Thanks!

**Comment by jovikao** [comment]
I have the same issue.
My app unzipped size is around 133M
But with datadog serverless-plugin-datadog (3.2.1) it becomes around 382 MB and showed the error:
`Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 401586124 bytes`

Python version: 3.8

**Comment by kwajiehao** [comment]
hi @babyhuey, do you mind sharing how you obtained the actual size of your deployment package with layers?

**Comment by greg-murray-newsela** [comment]
We've run into the same problem and will need to migrate to a [container image](https://aws.amazon.com/fr/blogs/aws/new-for-aws-lambda-container-image-support/)

[Serverless documentation is here](https://www.serverless.com/blog/container-support-for-lambda)
