### ISSUE TITLE
DD_SERVICE_MAPPING env var not working

### ISSUE THREAD

**Issue by dan-ilin** [DataDog/datadog-lambda-python#122]
It seems like the DD_SERVICE_MAPPING env var is currently not used by the module. The ddtrace library should be updated to 0.47.0 to allow use of this env var.

## Expected Behavior

Mappings from DD_SERVICE_MAPPING env var should set the APM views correctly instead of using the default values.

## Actual Behavior

Default values are used regardless of env var value.

## Steps to Reproduce the Problem

  1. Deploy Python lambda with datadog layer enabled (version 31)
  2. Set DD_SERVICE_MAPPING env var on lambda
  3. Generate traces
  4. Observe APM view names generated for traces - they will be the default generic names

## Specifications

  - Datadog Lambda Layer version: 31
  - Python version: 3.8

**Comment by tianchu** [comment]
Closing since ddtrace has already been updated to 0.48.0.
