### ISSUE TITLE
datadog_lambda.handler.handler not found when using AWS Lambda with Docker

### ISSUE THREAD

**Issue by samuelbaena** [DataDog/datadog-lambda-python#133]
## Expected Behavior
AWS Lambda with Docker working correctly and sending metrics to Datadog

## Actual Behavior
Lambda execution fails with error

## Steps to Reproduce the Problem

  1. Create docker image from dockerfile:
  ```
FROM python:3.8

WORKDIR /

COPY src/. .
RUN pip install boto3
RUN pip install datadog-lambda

ENV DD_LAMBDA_HANDLER main.handler
ENV DD_API_KEY xxxxxx
ENV DD_ENHANCED_METRICS true
ENV DD_TRACE_ENABLED true
ENV DD_FLUSH_TO_LOG true
ENV DD_LOGS_ENABLED true
ENV service test-dd-lambda-docker
ENV env testing

COPY --from=public.ecr.aws/datadog/lambda-extension:6 /opt/extensions/ /opt/extensions

CMD datadog_lambda.handler.handler
  ```
  Also tried with `CMD ["datadog_lambda.handler.handler"]`
 
 ```
import time
from ddtrace import tracer
from datadog_lambda.metric import lambda_metric
from datadog_lambda.wrapper import datadog_lambda_wrapper

@datadog_lambda_wrapper
def handler(event, context):
    # submit a custom span
    with tracer.trace("test_lambda_docker.example"):
        print('Hello World!')

    # submit a custom metric
    lambda_metric(
        metric_name='test_lambda_docker.example',
        value=1,
        timestamp=int(time.time()), # optional, must be within last 20 mins
        tags=['env:testing', 'service:test-dd-lambda-docker']
    )

    print("Testing")

    return {
        'statusCode': 200,
        'body': get_message()
    }

# trace a function
@tracer.wrap()
def get_message():
    return 'Hello from Lambda Docker!'
 ``` 
  2. Push to ECR 
  3. Instantiate AWS Lambda with such docker image
  4. Test with empty input

## Specifications

  - Datadog Lambda Layer version: 6
  - Python version: 3.8
  
## Stacktrace
  
```
{
  "errorMessage": "RequestId: xxxx Error: Runtime exited with error: exit status 127",
  "errorType": "Runtime.ExitError"
}
```
```
START RequestId: xxxxx Version: $LATEST
/bin/sh: 1: datadog_lambda.handler.handler: not found
EXTENSION	Name: datadog-agent	State: Registered	Events: [INVOKE,SHUTDOWN]
END RequestId: xxx
REPORT RequestId: xxx	Duration: 2505.82 ms	Billed Duration: 2506 ms	Memory Size: 128 MB	Max Memory Used: 18 MB	
RequestId: xxxx Error: Runtime exited with error: exit status 127
Runtime.ExitError
```

**Comment by nhinsch** [comment]
Hi there,

I think you might be using the wrong base image for your Lambda function. Your Dockerfile includes the line `FROM python:3.8`.  This image contains the Python runtime, but doesn't implement the Lambda runtime API. I recommend using one of the official Lambda base images provided by AWS. In your case that would be `FROM public.ecr.aws/lambda/python:3.8` or the equivalent `FROM amazon/aws-lambda-python:3.8`.

You will also want to make sure that you are copying your function code (and installing the Datadog Lambda Library) to the `/var/task` directory within your container image. If you are using the official base image, `WORKDIR` will already be set to `/var/task` so if you run a command like `pip install`, it will be run in that directory.

Here is some documentation from AWS that you may find helpful: https://docs.aws.amazon.com/lambda/latest/dg/images-create.html

Please let me know if you are able to resolve the issue!

**Comment by samuelbaena** [comment]
Hi @nhinsch, 
That worked, thank you so much for the support!

Best,
