### ISSUE TITLE
Docs insecure-by-default / Support secrets from Secrets Manager

### ISSUE THREAD

**Issue by jeffWelling** [DataDog/datadog-lambda-python#158]
## Expected Behavior

Datadog documentation for lambda layers should recommend and support a secure configuration, which does not involve hard-coding your Datadog API keys into your chalice config file. 

https://docs.datadoghq.com/serverless/installation/python/?tab=chalice

## Actual Behavior

Datadog documentation for lambda layers recommends an insecure configuration by default, asking the user to set the Datadog API keys in your chalice config file which is commonly committed to version control. It is against Best Practice to hard-code secrets such as the Datadog API key in plaintext in version control.

https://docs.datadoghq.com/serverless/installation/python/?tab=chalice

## Requested Behaviour

Datadog's Lambda layer could be updated to support pulling the Datadog API key from AWS Secrets Manager, and could update the documentation for the Datadog lambda layer to not recommend an insecure configuration by default. 

The name of the secret retrieved from Secrets Manager could default to 'DATADOG_API_KEY' and could be overridden with an environment variable to set the name of the secret to retrieve. In situations where the DATADOG_API_KEY is set in both the envvar and Secrets Manager I think it makes the most sense for Secrets Manager to win, with the thinking that the most secure secret should take precedence, but I could be swayed on this. 

## Steps to Reproduce the Problem

  1. Follow the Datadog documentation for lambda layers in chalice

## Specifications

  - Datadog Lambda Layer version: N/A
  - Python version: N/A
  
## Stacktrace
 
N/A

**Comment by tianchu** [comment]
@jeffWelling thanks for your feedback! This is a good idea. The only hesitation we have is that resolving credentials from secretes manager, kms or ssm would add a noticeable overhead on function's cold start time and not everyone prefers making that trade off.

I think we can update the doc with different ways to set the Datadog API key, explain the trade off and let users make their own decisions.

**Comment by jeffWelling** [comment]
Oh good point! Hm. 

Does the increased cold-start time have to be the case I wonder, maybe some way of only attempting to even check Secrets Manager (or other) if a flag is set could get us around that obstacle. 
I certainly don't want to add overhead to folks who wouldn't be using the feature, and of course not everyone would want such a trade-off, but for those that do want it would you decline to add such a feature? What if it was crafted by someone else and demonstrated to not add overhead when Secrets Manager wasn't in use?

What did you have in mind for docs changes? Perhaps I could help test out the workflow in mind? This is a problem I'm tackling just now so I can help if needed. 

One idea that was discarded early on was to use git-crypt to be able to commit the Datadog API key to the repo without having it in plaintext, the failure modes for this workflow are just too catastrophic to consider for production environments though.

**Comment by jeffWelling** [comment]
I've only now discovered this: https://github.com/DataDog/datadog-lambda-python/commit/54c8c6f1a6de43f3bf5e854e675ceb0b82c03dd0

Exploring the use of "DD_API_KEY_SECRET_ARN", this is perhaps what you hinted at above heh

**Comment by jeffWelling** [comment]
Confirmed, using that env var resolved our problem.

I've found that the documentation is available as a git repo, so I'll propose a PR to adjust the chalice installation docs shortly to recommend the more secure instrumentation method for chalice apps. 

If you had yet a different solution in mind as you hinted at before I would still be interested in hearing it, can't help but be curious hehe.
