### ISSUE TITLE
Using `DD_API_KEY_SSM_NAME` does not seem to work; `DD_API_KEY` does

### ISSUE THREAD

**Issue by bobwhitelock** [DataDog/datadog-lambda-python#209]
## Expected Behavior

Specifying the `DD_API_KEY_SSM_NAME` environment variable, with needed permissions according to https://github.com/DataDog/datadog-lambda-python#dd_api_key, and otherwise following instructions at https://docs.datadoghq.com/serverless/installation/python/?tab=terraform, should allow me to send metrics to Datadog using the API key stored in SSM with that name.

## Actual Behavior

I get this error when attempting to do this:

 ```
2022-02-28 13:05:15 UTC | DD_EXTENSION | WARN | failed to post http payload. code=403 host=lambda-http-intake.logs.datadoghq.com response={"errors":[{"status":"403","title":"Forbidden","detail":"API key is invalid"}]}
```

With no other useful output logged to CloudWatch to help debug this, and with `DD_LOG_LEVEL = "debug"` set as well.

If I make minimal tweaks to my Terraform to pull the API key from SSM at deploy time instead and set this as the `DD_API_KEY` environment variable, metrics are then successfully sent to Datadog.

## Steps to Reproduce the Problem

My Terraform code when this doesn't work, using `DD_API_KEY_SSM_NAME`, looks like this (simplified to just the pertinent stuff):

<details>

```terraform

resource "aws_iam_role" "my_lambda_role" {
  name = "my-lambda-role"

  assume_role_policy = jsonencode({
    Version : "2012-10-17",
    Statement : [
      {
        Action : "sts:AssumeRole",
        Principal : {
          Service : "lambda.amazonaws.com"
        },
        Effect : "Allow"
      }
    ]
  })
}

resource "aws_iam_role_policy" "my_lambda_policy" {
  name = "my-lambda-policy"
  role = aws_iam_role.my_lambda_role.id

  policy = jsonencode({
    Version = "2012-10-17",
    Statement = [
      {
        Effect = "Allow",
        Action = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents",
          "ssm:GetParameter",
          "kms:Decrypt",
        ],
        Resource = [
          "*"
        ]
      }
    ]
  })
}

data "archive_file" "my_lambda_zip" {
  type        = "zip"
  source_file = "path/to/lambda.py"
  output_path = "path/to/lambda.zip"
}

resource "aws_lambda_function" "my_lambda" {
  function_name    = "my-lambda"
  role             = aws_iam_role.my_lambda_role.arn
  filename         = "path/to/lambda.zip"
  source_code_hash = filebase64sha256("path/to/lambda.py")
  runtime          = "python3.9"
  handler          = "datadog_lambda.handler.handler"

  layers = [
    "arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Python39:52",
    "arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:20",
  ]

  environment {
    variables = {
      DD_LAMBDA_HANDLER = "my_lambda.main"
      DD_API_KEY_SSM_NAME = "/dev/my_namespace/DATADOG_API_KEY"
      DD_LOG_LEVEL = "debug"
    }
  }
}
```

</details>

If I make the following minimal changes to use `DD_API_KEY` and have the key from SSM extracted and used at deploy time instead, this does work and I'm able to send metrics to Datadog from this Lambda:

 ```diff
32,33d31
<           "ssm:GetParameter",
<           "kms:Decrypt",
48a47,50
> data "aws_ssm_parameter" "datadog_api_key" {
>   name = "/dev/my_namespace/DATADOG_API_KEY"
> }
>
65c67
<       DD_API_KEY_SSM_NAME = "/dev/my_namespace/DATADOG_API_KEY"
---
>       DD_API_KEY = data.aws_ssm_parameter.datadog_api_key.value
```

This suggests to me the key in SSM is OK and the rest of the integration with the Datadog Lambda layer is OK, but something is going wrong with the layer reading my key. However I can't see any other useful output to help debug what might be going wrong.

The code using `DD_API_KEY` does work fine and I can use this, I just would prefer to use `DD_API_KEY_SSM_NAME` as my key will then no longer need to be present in plaintext as an environment variable, and I will no longer need to redeploy my Lambda to use the new key if I need to rotate the key in SSM.

Let me know if you can see what the issue might be. Thanks for the help!

## Specifications

  - Datadog Lambda Layer version: 52
  - Python version: 3.9
  
## Stacktrace
  
N/A

**Comment by tianchu** [comment]
@bobwhitelock Sorry for the confusion, `DD_API_KEY_SSM_NAME` was only supported by this library for a legacy feature that submits custom metrics directly to Datadog by blocking the invocations. The readme has been cleaned up now.  

The recommended way to supply Datadog API key is storing the key in AWS Secrets Managers and set the secret ARN through the env var `DD_API_KEY_SECRET_ARN` on your Lambda functions. This way you avoid exposing the key and can easily rotate it without any update to the Lambda functions. See our [installation instructions for Python](https://docs.datadoghq.com/serverless/installation/python/).

**Comment by tianchu** [comment]
I'm closing since we don't have a plan to support `DD_API_KEY_SSM_NAME` when using the Datadog Lambda extension. Use `DD_API_KEY_SECRET_ARN` and Secrets Manager instead.

**Comment by bobwhitelock** [comment]
@tianchu Thanks for the clarification, that makes sense and we'll switch to use that env var

**Comment by djtecha** [comment]
I actually have to say this would be very helpful. We utilize SSM with a KMS key to handle all parameters and this creates a 1 off for us to use secrets manager instead. Additionally, things like the datadog forwarder are built to use SSM. Seems worth while to keep this type of thing consistent across products.
