### ISSUE TITLE
APIGateway tag data is not filtered when sending data in json error format

### ISSUE THREAD

**Issue by jairoufps** [DataDog/datadog-lambda-python#224]
## Expected Behavior
APIGateway tag data filtered, when sending data in json error format

## Actual Behavior
APIGateway tag data is not filtered, when sending data in json error format, the data is keep in format string without filtered

## Steps to Reproduce the Problem

  1.connect a APiGateway to lambda and send  a JSON in error format, for example
  ```
  {
  "user": {
    "extra_fields": {},
    "trace_id": "test"
    "card":{
    "number": 57556565656565,
    "security_code":123
    }
  },

  ```
  2. Then go to the datadog platform and look at the tag request, and it probably shows unfiltered string data because of this line of code of the lib
  ```
 try:
            parsed = json.loads(obj)
            return tag_object(span, key, parsed, depth)
        except ValueError:
            redacted = _redact_val(key, obj[0:5000])
            return span.set_tag(key, redacted)

  ```
  i do not know if json.loads fail this should be set a tags, because this string may contain information  that need be filtered
  
3. My datadog.yml in my lambda. 
  ```
apm_config:
  replace_tags:
    - name: "*"
      pattern: "/^[0-9]{3,4}$/"
      repl: ""

  ```

## Specifications

  - Datadog Lambda Layer version: 21
  - Python version: 3.8
  
## Stacktrace
  info saved in format string without filtered
  ```
"
  {
  "user": {
    "extra_fields": {},
    "trace_id": "test"
    "card":{
    "number": 57556565656565,
    "security_code":123
    }
  },
"
 ```

**Comment by tianchu** [comment]
Closing because the lack of activity.
