### ISSUE TITLE
Missing tags on some lambda logs

### ISSUE THREAD

**Issue by quanhd-lab** [DataDog/datadog-lambda-python#228]
## Expected Behavior

Getting all tags filled just like using with Forwarder function

## Actual Behavior
With some logs, it's nothing in tags
<img width="750" alt="Screenshot 2022-06-21 at 12 18 23" src="https://user-images.githubusercontent.com/107552083/174788601-748afb40-16e6-4054-8100-849759287d07.png">

All tags populated when using Forward function
<img width="727" alt="Screenshot 2022-06-21 at 12 30 54" src="https://user-images.githubusercontent.com/107552083/174789616-7cfa1cac-054d-48c0-8eb0-0aa638c06f42.png">

Logs in CloudWatch
<img width="1184" alt="Screenshot 2022-06-21 at 12 28 17" src="https://user-images.githubusercontent.com/107552083/174789654-ef893fd0-324a-40ff-b8eb-eda8c07eb5f1.png">

## Specifications

  - Datadog Lambda Layer version: I use library version 3.47.0
  - Python version: 3.8.10

**Comment by tianchu** [comment]
@quanhd-lab Thanks for flagging this issue. Unfortunately we need to take a deeper at your specific case (configurations, debugging logs, etc.). It's not something can be easily done over github. Do you mind [filing a support ticket](https://www.datadoghq.com/support/) instead?
