### ISSUE TITLE
Dual Shipping for Lambdas

### ISSUE THREAD

**Issue by djtecha** [DataDog/datadog-lambda-python#248]
Looks like there's a useful ability to dual ship for the standard agent. Wondering if this is planned to get added to lambdas? My issue currently is I have a lambda that runs in 1 account and I want the health of that lambda to ship to 1 DD sub org while the custom metrics it produces to ship to a different DD sub-org. Basically think about business metrics where one account is only used for management but they don't need to know about the service that creates those metrics at all.

**Comment by djtecha** [comment]
This could also be something like a option value in the lambda_metric function

```        
lambda_metric(
            'hits.acknowledged.count',
            value["seconds"],
            tags=['service:' + key, 'team:' + value["team"]],
            api_key="xxxxxxxxxxxxx"
        )

**Comment by tianchu** [comment]
See https://docs.datadoghq.com/serverless/configuration?tab=datadogcli#send-telemetry-to-multiple-datadog-organizations

**Comment by djtecha** [comment]
Trying additional formats... Not much luck

```
"{\"https://zulily-bizops.datadoghq.com\": [\"XXXXX\"]}"

```
{\"https://zulily-bizops.datadoghq.com\": [\"XXXX\"]}

**Comment by IvanTopolcic** [comment]
It should be working, you need all of the additional environment variables specified in the docs, not just the one you're using. There are different environment variables for metrics, logs, and traces, and they each have a slightly different format.

**Comment by djtecha** [comment]
Yea none of those work for a lambda here. I'm wondering if we just are passing those ENV values though using this wrapper? Tried digging through the src code and didn't see any reference to these ENV variables. Unless we're just passing all ENV values on to the bundled agent or something?

**Comment by tianchu** [comment]
Which method you are using to submit the custom metric? async using the extension or the forwarder? or synchronously/directly from the runtime using this library? https://docs.datadoghq.com/serverless/custom_metrics#overview

**Comment by djtecha** [comment]
I'm trying to use the extension. So in my python code I call this.

```
        lambda_metric(
            'mttr.resolved.count',
            int(value["seconds"]),
            tags=['service:' + key, 'team:' + value["team"]]
        )

**Comment by IvanTopolcic** [comment]
If you set `DD_LOG_LEVEL` to debug, are you seeing any errors or timeouts related to sending the metrics/traces/logs?

**Comment by djtecha** [comment]
So, I'm able to see all the metrics in the Org I use for the DD_API_KEY_SECRET_ARN value. But yea nothing coming through to the one I set DD_ADDITIONAL_ENDPOINTS to. I tried adding all things (though I only care to get the metrics in this case) and yea, nothing.

**Comment by djtecha** [comment]
Not sure if this helps but running with debug I see the host value is empty... but maybe that's something different

```
{
  "metric": "pagerduty.incidents.resolved.count",
  "tags": [
    "dd_lambda_layer:datadog-python39_4.62.0",
    "account_id:445473265646",
    "function_arn:arn:aws:lambda:us-east-1:XXXXX:function:stg_bizops_mttr",
    "architecture:x86_64",
    "aws_account:XXXX",
    "runtime:python3.9",
    "region:us-east-1",
    "version:4231dac1",
    "dd_extension_version:28",
    "functionname:stg_bizops_mttr",
    "memorysize:256",
    "resource:stg_bizops_mttr",
    "env:stg"
  ],
  "host": "",
  "interval": 10,
  "points": [
    {
      "sketch": {
        "summary": {
          "Min": 2,
          "Max": 2,
          "Sum": 2,
          "Avg": 2,
          "Cnt": 1
        }
      },
      "ts": 1661804630
    }
  ]
}

**Comment by tianchu** [comment]
Just a quick comment, `host` is expected to be empty for Lambda.

**Comment by IvanTopolcic** [comment]
Just a quick update, the reason this might not be working for you is because you don't need the escape character `\` for a serverless environment. I'm going to update the docs and add an example because I agree this is quite a confusing process.

**Comment by djtecha** [comment]
Ahh that totally works. Additionally, I didn't realize that the URL for the tracing side was different.

```
https://app.datadoghq.com vs https://trace.agent.datadoghq.com
```

I'll leave this here in case someone else wanted to see how the value should be rendered in the lambda env section

![Screenshot from 2022-09-23 09-20-12](https://user-images.githubusercontent.com/3084627/192009009-6bad9a90-e304-41af-a645-988f90c2bf85.png)

**Comment by djtecha** [comment]
By the way, it might be nice to carry the same level of non-plaintext API keys that we do for the DD_API_KEY_SECRET_ARN since it seems like I'm forced to pass additional API tokens in plain text.

**Comment by IvanTopolcic** [comment]
There's actually another new feature we support where you can add `_SECRET_ARN` to arbitrary environment variables and pass add those to Secrets Manager. For instance:

`DD_APM_ADDITIONAL_ENDPOINTS_SECRET_ARN`: `aws:secretsmanager:...`

And set the secrets manager value to your json blob, i.e `{"https://app.datadoghq.com":["..."] ...}`. These are relatively new features and are currently undocumented, which is something we're working on at the moment.

**Comment by IvanTopolcic** [comment]
Going to close this issue now, you can find more information on Serverless Dual Shipping here: https://docs.datadoghq.com/serverless/configuration/?tab=datadogcli#send-telemetry-to-multiple-datadog-organizations
