### ISSUE TITLE
Relax `datadog` version requirement?

### ISSUE THREAD

**Issue by stpierre** [DataDog/datadog-lambda-python#253]
## Expected Behavior

I should be able to use this library with a wider range of `datadog` library versions.

## Actual Behavior

In order to install the latest `datadog_lambda`, you must be running *exactly* `datadog==0.41`; you cannot run with a newer version. It would be nice if a range were supported.

`pyproject.toml` specifies:

```toml
datadog = "^0.41"
```

The `^` makes me suspect that someone perhaps intended to support `datadog>=0.41, <1`, but [poetry interprets `^` a bit differently when the first digit is a `0`](https://python-poetry.org/docs/dependency-specification/#caret-requirements). Happy to put in a PR to fix that if the desired behavior can be confirmed.

## Steps to Reproduce the Problem

  1. `pip install datadog_lambda==4.62.0 datadog==0.44.0`

## Specifications

  - Datadog Lambda Layer version: 62
  - Python version: Any

**Comment by Knifa** [comment]
Would appreciate this as well! We're having to run a fork to keep this happy alongside some of our internal libraries. 😅

**Comment by vschurink** [comment]
can this be updated please? our renovate borks every datadog or lambda pipy update because of this 'incompatibility'. This seems like an easy fix :)

**Comment by astuyve** [comment]
Sorry for the delay, thanks for the contribution! Will be releasing this shortly after the tests run.
