### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get' - wrapper.py

### ISSUE THREAD

**Issue by bissli82** [DataDog/datadog-lambda-python#295]
## Expected Behavior
Hi all,@joeyzhao2018 , I'm getting a few error messages coming from the wrapper.py, 
It comes as info and not as an error, that's my guess to why it was missed for awhile.
I assume this is because **our lambda function returns as string** and not an object(json?) which the extension expect so self.response is an str.

I think the issue was introduced by [this PR ](https://github.com/DataDog/datadog-lambda-python/pull/256)

![image](https://user-images.githubusercontent.com/6223793/213399181-c7c7dbf4-e739-494d-9bce-9536f150b384.png)

## Steps to Reproduce the Problem

As far as I can see, any lambda run which returns a string 

## Specifications

  - Datadog Lambda Layer version: 35
  - Python version: 3.9
  
## Stacktrace
  
  ```
File "/opt/python/lib/python3.9/site-packages/datadog_lambda/wrapper.py", line 281, in _after
and self.response.get("principalId")
AttributeError: 'str' object has no attribute 'get'
  ```

**Comment by joeyzhao2018** [comment]
Merged a fix (https://github.com/DataDog/datadog-lambda-python/pull/296). Pending layer release.
