### ISSUE TITLE
Bundling

### ISSUE THREAD

**Issue by tefmartins** [DataDog/datadog-lambda-python#306]
This is a question, I was not able to find the correct outlet to make questions. 
This lib requires aws-cdk, which is 290mb and exceeds the size allowed to lambdas. What is the recommended way of bundling when using this lib? Does it need to depend on the whole aws-cdk lib?

**Comment by astuyve** [comment]
Hi @tefmartins -
Thanks for reaching out!

As far as I know this library doesn't depend on the CDK ([dependencies here](https://github.com/DataDog/datadog-lambda-python/blob/main/poetry.lock)).

As for the size of the payload, it is around 23mb uncompressed. We have a CI check to ensure it is not greater than 7mb compressed and 24mb uncompressed, which you can see [here](https://github.com/DataDog/datadog-lambda-python/blob/main/scripts/check_layer_size.sh#L11-L12) is [passing](https://github.com/DataDog/datadog-lambda-python/actions/runs/4167526420/jobs/7213222964#step:7:1) on our latest release.

I'm not sure how much more helpful I can be, perhaps you could share a minimally reproducible example which causes the size issue you've mentioned here?

Thanks!

**Comment by astuyve** [comment]
Closing this as there's been no update for several weeks. Please feel free to reach out with some more code or an example which we can test if this is still occurring.

Thanks!
