### ISSUE TITLE
Initial crash when merge xray traces is enabled

### ISSUE THREAD

**Issue by blaxter** [DataDog/datadog-lambda-python#308]
## Expected Behavior
Do not crash

## Actual Behavior
Crash at the start of every request with merge_xray_traces enabled but no `_X_AMZN_TRACE_ID` present on the event triggering the lambda

## Steps to Reproduce the Problem

  1. Create a hello world lambda with Datadog construct having `enable_merge_xray_traces=True` and `enable_datadog_tracing=True`
  1. Trigger the lambda, e.g., using the 'Test' section in its aws console section

## Specifications

  - Datadog Lambda Layer version: 40
  - Python version: 68
  
## Stacktrace
  
  ```
 Traceback (most recent call last):
 File "/var/task/datadog_lambda/wrapper.py", line 247, in _before
   set_dd_trace_py_root(trace_context_source, self.merge_xray_traces)
 File "/var/task/datadog_lambda/tracing.py", line 542, in set_dd_trace_py_root
   context = dict(dd_trace_context)
 TypeError: 'NoneType' object is not iterable
  ```

Probably the fix required is something like this:
```
$ git diff
diff --git a/datadog_lambda/tracing.py b/datadog_lambda/tracing.py
index 19ef8c0..31013ac 100644
--- a/datadog_lambda/tracing.py
+++ b/datadog_lambda/tracing.py
@@ -457,7 +457,7 @@ def extract_dd_trace_context(
     else:
         # AWS Lambda runtime caches global variables between invocations,
         # reset to avoid using the context from the last invocation.
-        dd_trace_context = _get_xray_trace_context()
+        dd_trace_context = _get_xray_trace_context() or {}
         if dd_trace_context:
             trace_context_source = TraceContextSource.XRAY
     logger.debug("extracted dd trace context %s", dd_trace_context)
```

**Comment by blaxter** [comment]
> @blaxter Thanks for the report! Could you confirm whether the error break your Lambda function or just the Datadog tracing? I'm asking because the code where the error originates from is protected by a global try...except...
> 
> https://github.com/DataDog/datadog-lambda-python/blob/3e09ff472f0e23fa28af21f86070456945c34318/datadog_lambda/wrapper.py#L227
> 
> According to our testing, it would only break the Datadog tracing, while it should NOT crash your application.

Yes, that's right. The function still works but there are no x-ray merged traces.

**Comment by tianchu** [comment]
@blaxter could you try upgrade to the [latest version](https://github.com/DataDog/datadog-lambda-python/releases/tag/v69)? We believe that issue was due to the recently added Lineage field to X-Ray tracing header, and the issue should have been fixed in that version.

**Comment by blaxter** [comment]
With the last version this error is fixed though now I'm getting [a warning in all my lambdas](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/aws_lambda/patch.py#L74), I'm going to disable apm until I can investigate further.

Closing the issue as the original problem is fixed.
