### ISSUE TITLE
Support for python 3.10

### ISSUE THREAD

**Issue by CharlesPerrotMinotHCHB** [DataDog/datadog-lambda-python#314]
## Expected Behavior
Have a Datadog lambda layer using python 3.10

## Actual Behavior
Currently, there's not AWS lambda for python 3.10

## Specifications
  - Datadog Lambda Layer version: ##
  - Python version: 3.10
  
## Notes
AWS Lambda Runtime should arrive soon (if announcement is correct, in the next few weeks):
https://github.com/aws/aws-lambda-base-images/issues/31#issuecomment-1448638312
So opening the request to follow that change, and potentially have some preliminary work done!

**Comment by astuyve** [comment]
Hi @CharlesPerrotMinotHCHB,
Thanks for reaching out. We're actively working with AWS on the new base image for Python 3.10 and will update this ticket when that can be released.

Unfortunately we won't be able to publish a lambda layer with support for 3.10 until AWS Lambda officially supports it (as we rely on their `compatible-runtimes` flag).

Thanks again!
AJ

**Comment by astuyve** [comment]
3.10 support was released in [71](https://github.com/DataDog/datadog-lambda-python/releases/tag/v71)
