### ISSUE TITLE
LambdaLoggerHandler formatter is overwritten when DD_LOGS_INJECTION is true

### ISSUE THREAD

**Issue by terkalma** [DataDog/datadog-lambda-python#315]
## Expected Behavior

A user should be able to bring their own LogFormatter when turning Datadog logs injection on.

## Actual Behavior

The formatter for `LambdaLoggerHandler` is overwritten [here](https://github.com/DataDog/datadog-lambda-python/blob/411b29fcc710c96681ec7f03b034780ad43c37e0/datadog_lambda/tracing.py#L548)

## Steps to Reproduce the Problem

We use use [json-logger-python](https://github.com/madzak/python-json-logger) (listed [here](https://docs.datadoghq.com/logs/log_collection/python/) as well) to change the formatter of `LambdaLoggerHandler`.
This formatter would work well with datadog correlation ids, the trace variables show up nicely when testing this with another handler.
 
1. in your lambda code, change the formatter of  `LambdaLoggerHandler`.

```
log = logging.getLogger()
    for handler in log.handlers:
        if handler.__class__.__name__ == 'LambdaLoggerHandler':
            handler.setFormatter(CustomJsonFormatter())
```
2. Change DD_LOGS_INJECTION to "true"
3. The formatter will be changed by datadog, even though this would not be necessary

## Specifications

  - Datadog Lambda Layer version:  any
  - Python version: 3.8.10

**Comment by terkalma** [comment]
@tianchu this makes sense, thank you! Not sure if this is something we missed during the transition from the lambda forwarder to the Datadog Lambda Extension. 

Would it not make sense to default `DD_LOGS_INJECTION` to false when using the Datadog Lambda Extension

**Comment by tianchu** [comment]
@terkalma no, that's totally an oversight from our side, just prioritized a ticket for next sprint to ignore `DD_LOGS_INJECTION` (and treat it as false) when using the extension.

**Comment by tianchu** [comment]
We didn't yet make the change in the library directly, however, we did default it to false now for ppl using the serverless plugin https://github.com/DataDog/serverless-plugin-datadog/pull/396. Given that there aren't many others similar reports, I'm closing this issue here.
