### ISSUE TITLE
Exclude Log Lines

### ISSUE THREAD

**Issue by djtecha** [DataDog/datadog-lambda-python#316]
Maybe I'm missing this here but is there a way to exclude the lambda extension from shipping log lines? I know a lot of people hate the constant spam of `START RequestId:` in a lambda or only want to ship WARN and above. Is this possible via ENV variable?

**Comment by djtecha** [comment]
NVM answered my own question :)

```
      "DD_LOGS_CONFIG_PROCESSING_RULES" : "[{\"type\": \"exclude_at_match\",\"name\": \"lambda_info\",\"pattern\": \"^(START|REPORT|END)\"}]"

**Comment by joeyzhao2018** [comment]
Hi @djtecha , you can use env variable `DD_LOG_LEVEL` to change the log level. To ship WARN and above you can use `DD_LOG_LEVEL = WARN` [more details](https://docs.datadoghq.com/agent/troubleshooting/debug_mode/?tab=agentv6v7#agent-log-level).
You might also want to turn `DD_TRACE_DEBUG` to `false` as it might add additional logging. [more detail](https://docs.datadoghq.com/serverless/troubleshooting/#collect-debugging-logs)

**Comment by djtecha** [comment]
Hey @joeyzhao2018 I think that only applies to the DD agent logging level. Here's a case where this is the built-in lambda noise that you can't avoid getting created.

**Comment by joeyzhao2018** [comment]
Sorry I misunderstood the question. 🤦 Yeah, I believe the [DD_LOGS_CONFIG_PROCESSING_RULES](https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=environmentvariable) can help filter out those lambda generated logs.
