### ISSUE TITLE
Support EventBridge events going into SQS and then into Lambda

### ISSUE THREAD

**Issue by michaeldimchuk** [DataDog/datadog-lambda-python#317]
## Background
We use EventBridge quite heavily, but we don't directly push events from the bus to the Lambda function (trying to avoid asynchronous invocations because those don't work very well with retries), but rather we push the event to an SQS queue, which we then consume from the Lambda function. Additionally, we transform the EventBridge event with an input transformation rule that pulls our the `detail` property of the event, so the exact payload that we sent from the client (including the `_datadog` property) is pushed into the SQS queue.

There are two main issues with this pattern and this library:
- The default EventBridge tracer does not pick up the event because it's looking for the `detail._datadog` field, when in reality it's just `_datadog` (and because the Lambda invocation source isn't `eventbridge`)
- The default SQS tracer only accounts for the possibility of SNS events being in the queue, not EventBridge events

I've tried to sort of hack a solution together by creating a wrapper around the `datadog_lambda.handler.handler` callable, which injects the `_datadog` attributes from the SQS message `body` into the `messageAttributes` instead, but this creates a really strange flame graph as DataDog isn't able to correlate a trace coming from `events.putevents` and landing in an `aws.sqs` invocation.

## Possible Solutions
1. Similar to how `extract_context_from_sqs_or_sns_event_or_context` already accounts for the possibility of SNS events being in SQS queues, support can be added for EventBridge, allowing for proper propagation of such events and flame graphs being connected between an EventBridge event being published and it being consumed from an SQS queue.<br>
The only issue with this approach is that it may not account for the input transformation done on the EventBridge event, which at least in our case, pulls out the `detail` attribute, which contains the trace data DataDog is looking for. This may need some customizable extraction logic, as different companies may be doing this differently.

2. Allow for the custom trace extractor to be executed, but still run all the other default extractors defined in `tracing.py` if the custom trace extractor couldn't figure out where the trace came from.<br>
The current implementation of the Lambda wrapper allows for a custom trace extractor to be used here [wrapper.py#L165](https://github.com/DataDog/datadog-lambda-python/blob/main/datadog_lambda/wrapper.py#L165), which is then utilized in [tracing.py#L411](https://github.com/DataDog/datadog-lambda-python/blob/main/datadog_lambda/tracing.py#L411).<br>
The main issue here, is that if the custom trace extractor is provided, it's expected to accurately resolve the trace, because the [next section of the if block](https://github.com/DataDog/datadog-lambda-python/blob/main/datadog_lambda/tracing.py#L417) is an `elif`. <br>
This means that if I wanted to add some custom trace extraction logic for some components that are custom, I would then have to either re-create all of the tracing logic already defined in `tracing.py`, or import that and call `extract_dd_trace_context` myself as a backup, which creates other issues I'd prefer to avoid (specifically potential for circular dependencies, and type checking errors this will likely raise).

**Comment by astuyve** [comment]
Hi @michaeldimchuk!

Thanks so much for reaching out with your very detailed support ticket.

Tracing through EventBridge + SQS (and other common serverless services) is on our roadmap and I'm happy to update this ticket when it is released.

We can definitely look into custom trace extraction improvements as well.

I'll keep this open and someone will update it as work begins or if we have questions around developer ergonomics which we'd like to have the community provide input on.

Thanks again!

**Comment by astuyve** [comment]
Hi @michaeldimchuk!

This is now released in [4.78.0](https://github.com/DataDog/datadog-lambda-python/releases/tag/v78), and layer version 78!

We'll update our developer tools soon.

Thanks so much!
