### ISSUE TITLE
"Runtime.MarshalError" when using custom authorizers on python 3.7

### ISSUE THREAD

**Issue by Wesitos** [DataDog/datadog-lambda-python#326]
## Expected Behavior

When invoking a function which returns an "authorizer" like dictionary (has non-falsy "principalId" and "policyDocument" fields) using python3.7, the function should not return an error

## Actual Behavior

A "Runtime.MarshalError" is returned because the python 3.7 lambda runtime cannot serialize `bytes` values (this feature was added in version 3.8)

## Steps to Reproduce the Problem

Invoke a lambda function that returns `{"principalId" :" ", "policyDocument": " "}` using the python3.7 runtime.

You can also clone this [serverless project that replicates the bug](https://github.com/Wesitos/sls-datadog-python37-bug).
1. Deploy setting the `DATADOG_API_KEY` env variable to set a valid api key
2. invoke the `failing` function. It'll return an error.

A `working` function is also provided that workarounds the error by patching the lambda runtime code.

## Specifications

  - Datadog Lambda Layer version: v71
  - Python version: 3.7
  
## Stacktrace
  
 No stackTrace

**Comment by Wesitos** [comment]
Related to https://github.com/DataDog/datadog-lambda-python/pull/325

**Comment by joeyzhao2018** [comment]
Thank you for opening the issue. I have tested and merged the PR https://github.com/DataDog/datadog-lambda-python/pull/325. We will include this fix in next release soon.

**Comment by joeyzhao2018** [comment]
[datadog-lambda 4.72.0](https://pypi.org/project/datadog-lambda/) includes the fix.
