### ISSUE TITLE
KeyError `x-datadog-trace-id` when DD_ENABLE_TRACE is false

### ISSUE THREAD

**Issue by salehshehata-RL** [DataDog/datadog-lambda-python#332]
## Expected Behavior

The datadog datalayer doesn't try to get the correlation ids if tracing is off.

## Actual Behavior
The datadog datalayer tries to get the correlation ids if tracing is off, and throws a KeyError.

## Steps to Reproduce the Problem

  1. Create an aws lambda
  2. Set the `DD_LAMBDA_HANDLER` to `the _lambda_function`
  3. Set the lambda handler to `datadog_lambda.handler.handler`
  4. Set `DD_ENABLE_TRACE` to "false".

## Specifications

  - Datadog Lambda Layer version:  4.66 & 4.72.0
  - Python version:  3.7, 3.9
  
## Stacktrace
  
  ```
023-05-16 08:56:14 Traceback (most recent call last):
2023-05-16 08:56:14   File "/opt/python/lib/python3.9/site-packages/datadog_lambda/wrapper.py", line 234, in _before
2023-05-16 08:56:14     set_correlation_ids()
2023-05-16 08:56:14   File "/opt/python/lib/python3.9/site-packages/datadog_lambda/tracing.py", line 513, in set_correlation_ids
2023-05-16 08:56:14     span.trace_id = int(context[TraceHeader.TRACE_ID])
2023-05-16 08:56:14 KeyError: 'x-datadog-trace-id'
  ```

**Comment by astuyve** [comment]
Hi @salehshehata-RL - Thanks for reaching out!

While we investigate this, could you help clear something up for me?

I think there may be an issue here; we use `DD_TRACE_ENABLED` to enable or disable tracing. Can you confirm you're setting `DD_TRACE_ENABLED=false` and still experiencing this issue?

Thanks!
AJ

**Comment by joeyzhao2018** [comment]
👀  working on a fix. This seems to be a bug happening when neither datadog tracing nor x-ray was enabled.

**Comment by salehshehata-RL** [comment]
@joeyzhao2018 how can we disable x-ray?

**Comment by salehshehata-RL** [comment]
@astuyve Yes the issue is still happening when `DD_TRACE_ENABLED=false` the code that is causing that is: https://github.com/DataDog/datadog-lambda-python/blob/a8949387c49575f84970b429913e9ca7f5079454/datadog_lambda/tracing.py#L566

@joeyzhao2018 any ETA on the fix?

**Comment by salehshehata-RL** [comment]
I think that PR should fix it, is there an ETA on release?

**Comment by astuyve** [comment]
Hi, this is released in [v73](https://github.com/DataDog/datadog-lambda-python/releases/tag/v73)

Please feel free to reach out with any other issues.
Thanks!!

**Comment by salehshehata-RL** [comment]
@astuyve this wasn't release for Python 3.7
