### ISSUE TITLE
Unit specification

### ISSUE THREAD

**Issue by joshverma** [DataDog/datadog-lambda-python#363]
Hello. Is there a way to specify the unit type (ex: milliseconds) when sending a metric using `lambda_metric`?

Thanks.

**Comment by agocs** [comment]
Hey @joshverma . Not in the code. The best way to specify the unit type is in the Datadog UI. In the left hand panel, go into `Metrics > Summary`, search for the metric name, click `Edit` on the Metric Metadata, and set the unit there. Please reach out to support if you need help with this; they can help you out a lot better than I can in a GIthub issue.
