### ISSUE TITLE
URLLib3 is pinned below version 2

### ISSUE THREAD

**Issue by LewisCowlesMotive** [DataDog/datadog-lambda-python#376]
## Expected Behavior

Stable dependencies that don't downgrade without explanation.

## Actual Behavior

Urllib3 downgrades from 2.x after installing datadog-lambda

## Steps to Reproduce the Problem

  1. poetry init
  2. poetry add boto3
  3. poetry install
  4. poetry lock
  5. poetry show | grep urllib
  6. poetry add datadog-lambda
  7. poetry install
  8. poetry lock
  9. poetry show | grep urllib

## Specifications

The below details are provided as asked for, but are irrelevant

  - Datadog Lambda Layer version: N/A
  - Python version: 3.11
  
## Stacktrace
  
N/A; this bug is in the packaging 🙃

**Comment by astuyve** [comment]
Hi, thanks for reaching out!

Yes this is the result of #329 and caused by a dependency on botocore, which also is pinned below v2 of urllib3. This seems to cause other issues with [amazon's internal infrastructure](https://github.com/boto/botocore/issues/2926#issuecomment-1538900780).

You can follow along this thread for more: https://github.com/boto/botocore/issues/2926

**Comment by LewisCowlesMotive** [comment]
Their latest comment is confusing then https://github.com/boto/botocore/issues/2926#issuecomment-1753332063
It mentions now being pinned below 2.1

**Comment by LewisCowlesMotive** [comment]
It seems upon further examination, your python range may be why you have a simpler limit
https://github.com/boto/botocore/blob/1.31.63/setup.py#L29

**Comment by astuyve** [comment]
[Only for 3.10 and above](https://github.com/boto/botocore/blob/develop/setup.cfg#L8).
This library has to support 3.7 and above, which is why we can't change the pin yet.

I'm more than happy to remove it when AWS can fully support all current Lambda runtimes.

**Comment by LewisCowlesMotive** [comment]
Do you think you'd accept a patch for using https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies so that 3.10+ can use <2.1?

**Comment by astuyve** [comment]
We would but that change is complex as our build process isn't presently aware of variations across multiple poetry.lock files, which may be tricky to add. Additionally it may complicate our coordination with dd-trace-py. But I'm happy to test out whatever you'd like to contribute.

**Comment by LewisCowlesMotive** [comment]
lets see if / where it blows up and revisit 😄

**Comment by LewisCowlesMotive** [comment]
@astuyve it looks like it passes tests; flakes on integrations are AWS permissions related, no idea how you'll overcome those, but they do not relate to the python code.

**Comment by astuyve** [comment]
Yeah, I have to run them myself. I'll let you know, thanks!

**Comment by LewisCowlesMotive** [comment]
So you're importing from an internal package and it breaks things... Can you describe what that import is used for?

**Comment by astuyve** [comment]
Hi, no sorry for the missing context - it's thrown by botocore (same error we've been discussing).

I'll see if we can upgrade our version of botocore to account for it in 3.10. The patch looks good in 3.11 though.

**Comment by astuyve** [comment]
Hi, to update - I created a brand new serverless application using python3.10, boto3 (from the 3.10 runtime), and my own version of urllib3==2.0.7, and *without* datadog's instrumentation.

It crashes with the same error:
![image](https://github.com/DataDog/datadog-lambda-python/assets/1598537/251b9dd2-f51e-422e-8a5b-eab76a09ed8a)
![image](https://github.com/DataDog/datadog-lambda-python/assets/1598537/a3200fe3-63d8-4110-bf3e-1afa5ea02cdb)

Python 3.11 works fine though.

Looks like it has a newer version of botocore/boto3:
![](https://github.com/DataDog/datadog-lambda-python/assets/1598537/a5dbf830-123f-47ff-978b-8c1241b1aa0b)
[link](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)
Instead I've opened #380 which allows urllib3 2.x for python 3.11 only and marks it as optional.

**Comment by astuyve** [comment]
Additionally I've opened https://github.com/aws/aws-lambda-base-images/issues/118 to track this fix in the Lambda runtime itself

**Comment by LewisCowlesMotive** [comment]
Can I ask when the new release will be cut?
