### ISSUE TITLE
_datadog field being injected into payloads after python version upgrade

### ISSUE THREAD

**Issue by luca579** [DataDog/datadog-lambda-python#495]
## Context

When upgrading from python 3.8 to python 3.11, a new _datadog field is being injected into my event payloads whenever I invoke lambda_metric in one of my lambdas and then sent them to a kinesis stream. This behavior didn't exist before the version upgrades and I was not able to find concrete references to it in the official documentation.

Is this behavior something that got added to this library over time?
Is there a setting to disabled the injection without disabling the enhanced metrics?  If not, can I just safely ignore and/or delete this field?

My sincere apologies in case I'm missing something here.
Thanks! 

## Architecture

Lambda 1 (where lambda_metric is invoked) --> Kinesis stream (where the payloads are probably being injected(?)) --> Lambda 2 (payloads already have the _datadog field when they reach here)

## Specifications
Datadog Lambda layer version: from 35 to 94
Python version: from 3.8 to 3.11
datadog_lambda version: to 5.94.0
ddtrace version: to 2.8.3

Serverless AWS lambda

**Comment by astuyve** [comment]
Hi, yes 35 to 94 is quite the upgrade!

We announced this in [2022](https://www.datadoghq.com/blog/monitor-aws-fully-managed-services-datadog-serverless-monitoring/) with docs links in the blog post.

This field is used to trace through Kinesis. Your code shouldn't necessarily care about it (eg: you can ignore it).

If you're not using APM at all, you can disable it with `DD_TRACING_ENABLED: false`.

Thanks!
AJ
