### ISSUE TITLE
You are not authorized to perform: lambda:GetLayerVersion in AWS ap-southeast-1 region

### ISSUE THREAD

**Issue by jumpeinoda** [DataDog/datadog-lambda-python#498]
## Expected Behavior
I should be able to use lambda runtime layer in ap-northeast-1 region of AWS

## Actual Behavior
Deploying the [Cloudformation template ](https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml)results in this error only in this region.
You are not authorized to perform: lambda:GetLayerVersion. even though my AWS Role has Administrator permissions

## Steps to Reproduce the Problem

  1. Deploy the [Cloudformation template](https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml) to ap-northeast-1
  2. AWS Console will error out saying You are not authorized to perform: lambda:GetLayerVersion.

## Specifications

  - Datadog Lambda Layer version: 55
  - Python version: 3.9
  
## Stacktrace
  
  ```
  "User: xxxx is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:ap-northeast-1:464622532012:layer:Datadog-Forwarder:55 because no resource-based policy allows the lambda:GetLayerVersion action (Service: Lambda, Status Code: 403, Request ID: xxxxxx)" (RequestToken: xxxxx, HandlerErrorCode: AccessDenied)
  ```

This is referenced in https://github.com/DataDog/datadog-lambda-python/issues/240 also.

**Comment by astuyve** [comment]
Hi @jumpeinoda - thanks for reaching out!
This repository hosts the datadog lambda tracer for python. It does not deploy or create the datadog log forwarder, or that cloudformation template.

You will want to reach out to customer support and/or file a support ticket in the [datadog log forwarder](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring) repository.

Anecdotally it looks like v55 was not published to ap-northeast-1.

Thanks!
