### ISSUE TITLE
`flush_stats` can't be called without a Lambda context

### ISSUE THREAD

**Issue by nr-synth** [DataDog/datadog-lambda-python#515]
## Expected Behavior
`metric.flush_stats` has an optional `lambda_context` argument, defaulting to `None`.

Omitting this argument shouldn't cause issues, and didn't in earlier versions of the library.

## Actual Behavior
Exception thrown: `builtins.UnboundLocalError: local variable 'tags' referenced before assignment`

## Steps to Reproduce the Problem

  1. `metric.flush_stats()`

## Specifications

  - Datadog Lambda Layer version: v6.98.0
  - Python version: 3.10
  
## Stacktrace
  
```
Traceback (most recent call last):
  [...]
  File "/home/lambda/[...]", line 55, in send
    flush_stats()
  File "/home/lambda/datadog_lambda/metric.py", line 136, in flush_stats
    extension_thread_stats.flush(tags)
UnboundLocalError: local variable 'tags' referenced before assignment
```

**Comment by purple4reina** [comment]
Thanks for reporting this @nr-synth, this is indeed a bug in the library. I'll get started working on a fix.

However, you shouldn't need to ever call this method manually yourself. The datadog wrapper will do it for you after each invocation. Are you calling this manually?

**Comment by purple4reina** [comment]
The change has been merged and will go out with our next release. Thanks again for reporting this!
