### ISSUE TITLE
Add support for datadog-lambda extension in China

### ISSUE THREAD

**Issue by kent-b** [DataDog/datadog-lambda-python#523]
## Expected Behavior
Deploying lambda to cn-north-1 works the same as global AWS partition.

## Actual Behavior
Lambda fails to be created.  Datadog extension layers do not exist in China.  Attempts to access global AWS partition from China results in a 403.

Is it possible to publish the layers in China so that there is parity with the rest of the AWS regions?

**Comment by DylanLovesCoffee** [comment]
Hey @kent-b 👋 This is a known issue where we do not currently publish our layers in AWS China. Could you open up a support ticket with [our team](https://www.datadoghq.com/support/) so we can look further into your request?

**Comment by kent-b** [comment]
Will do, thanks!
