### ISSUE TITLE
No module named 'ddtrace._trace.utils_botocore' after upgrading to lambda layer 99

### ISSUE THREAD

**Issue by babyhuey** [DataDog/datadog-lambda-python#525]
## Expected Behavior
App works and responds

## Actual Behavior
Failure. Stack trace below.

Rolling back to version 98 fixes all issues

## Steps to Reproduce the Problem

  1. Set lambda layer to 99
  1. Set extension to arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:65
  1. Try to do anything

## Specifications

  - Datadog Lambda Layer version:  arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Python311:99
  - Python version: 3.11
  
## Stacktrace
  
`[ERROR] Runtime.ImportModuleError: Unable to import module 'datadog_lambda.handler': No module named 'ddtrace._trace.utils_botocore'`

**Comment by purple4reina** [comment]
Hey @babyhuey, can you share the full traceback you're getting?

**Comment by purple4reina** [comment]
Hi again @babyhuey. After consulting with the team, we think this could be caused by having multiple versions of ddtrace installed. Are you by chance also including ddtrace in your dependencies? If so, does removing it as a dependency fix the issue?

**Comment by babyhuey** [comment]
> Hi again [@babyhuey](https://github.com/babyhuey). After consulting with the team, we think this could be caused by having multiple versions of ddtrace installed. Are you by chance also including ddtrace in your dependencies? If so, does removing it as a dependency fix the issue?

Yep. Apologies. Didn't know my engineers added it. Thanks for pointing me there!

**Comment by purple4reina** [comment]
No worries, more than happy to help.

Hope this can help others who might see this error message in the future

> No module named 'ddtrace._trace.utils_botocore' 

The solution is to ensure that you are not also packaging a version of `ddtrace` or `datadog-lambda` in your dependencies.
