### ISSUE TITLE
You are not authorized to perform: lambda:GetLayerVersion in AWS me-south-1 region 

### ISSUE THREAD

**Issue by aashitvyas** [DataDog/datadog-lambda-python#64]
## Expected Behavior
I should be able to use lambda python3.7 runtime layer in me-south-1 region of AWS 

## Actual Behavior
AWS Console is giving me an error saying that `You are not authorized to perform: lambda:GetLayerVersion.` even though my AWS Role has Administrator permissions 

## Steps to Reproduce the Problem

  1. Create AWS Lambda function in me-south-1 with run time python 3.7
  2. Try to add layer with the below ARN after choosing *Provide a layer version ARN* option in the AWS Console  
`arn:aws:lambda:me-south-1:464622532012:layer:Datadog-Python37:11`
  3. AWS Console will error out saying `You are not authorized to perform: lambda:GetLayerVersion.`

## Specifications

  - Datadog Lambda Layer version: 11
  - Python version: 3.7

**Comment by agocs** [comment]
Hello, we'll deploy the Python layer to me-south-1 later today / tomorrow at the latest. If you need to, you should be able import the Python package from PIP in the mean time.

**Comment by aashitvyas** [comment]
@agocs No worries, Please let us know once you deploy it so we can try again from our end.

**Comment by agocs** [comment]
Hey, I wanted to follow up with you. I'm waiting for our infrastructure team to enable me-south-1 (and af-south-1) so I can push the layer.

**Comment by aashitvyas** [comment]
@agocs , Thank you for the update. No worries, Let us know once the update is pushed by notifying us over here so we will do the deployment on our end

**Comment by aashitvyas** [comment]
@agocs  any updates on this issue ? Our deployments are still on hold

**Comment by agocs** [comment]
@aashitvyas Hey, unfortunately our infra team says it's going to take weeks to enable me-south-1 in our prod AWS account. I think your best bet for the time being will be to install the library from PyPI and bundle it with your lambda package. https://github.com/DataDog/datadog-lambda-layer-python#pypi

Let me know if I can assist you with this. I'll keep an eye on the infra team and will let you know when we're able to push the layer.

**Comment by aashitvyas** [comment]
@agocs Hi, Is there any update on this ?

**Comment by ryan1336** [comment]
Getting this error for 
arn:aws:lambda:us-east-1:464622532012:layer:Datadog-python37:28

on us-east-1
