### ISSUE TITLE
2.19.0 py3 whl was updated in pypi, now includes different install_requires

### ISSUE THREAD

**Issue by akursar** [DataDog/datadog-lambda-python#83]
## Expected Behavior

releases on pypi are expected to be immutable

## Actual Behavior

today's 2.19.0 py3 whl is a different one than was there 2 days ago, and is different than the v19 tag in github

https://github.com/DataDog/datadog-lambda-python/blob/v19/setup.py#L32

## Steps to Reproduce the Problem

`pip3 install datadog-lambda==2.19.0` now reports it requires datadog==0.38.0, when it used to (and still shows in github) require datadog==0.32.0

## Specifications

  - Datadog Lambda Layer version: 2.19.0
  - Python version: 3

**Comment by Czechh** [comment]
Hey @akursar  - thanks for bringing this up! I suggest you upgrade to v21 (v2.21.0) or use a layer instead.

I'm not sure how the package version v19 was modified, they should be immutable. Apologies. Trying to build v19 again and replace the module fails (as expected) as the version already exists.

**Comment by Czechh** [comment]
@akursar - thanks for the issue, I'll close as the new version fixes this problem.
