### ISSUE TITLE
Update ddtrace to fix bug in Django view method resolution order

### ISSUE THREAD

**Issue by piohhmy** [DataDog/datadog-lambda-python#84]
Received this email from Datadog support:

> On August 18th, 2020, Datadog identified a bug in the Django Instrumentation of the Python APM Tracing Client that could cause the Django View’s method resolution order to skip inherited methods. Django view classes that inherit from multiple parent classes are potentially impacted. We have addressed the issue and you should update to the latest version of the Python APM Tracing client. Please refer to the “Recommended action” section below for remediation steps.

> Recommended action:

> Update the Python APM Tracing Client to the latest version using pip:

> pip install ddtrace==0.41.2

> This issue affects only ddtrace Python package version from 0.34.0 to 0.41.1. If you are unable to upgrade to the latest version (0.41.2), you should upgrade to the below patch versions corresponding to your installed minor version:

>0.41.2
>0.40.2
>0.39.2
>0.38.4
>0.37.3
>0.36.3
>0.35.2
>0.34.2
>If you have any additional questions, please reach out to our support team at support@datadoghq.com.

It appears this project still has ddtrace pinned to 0.40.0.

**Comment by tianchu** [comment]
@piohhmy Do you mind posting the issue to https://github.com/DataDog/dd-trace-py?

**Comment by piohhmy** [comment]
If I understand correctly, the issue is fixed in https://github.com/DataDog/dd-trace-py but this project's dependencies just need to be updated to the patched version here: https://github.com/DataDog/datadog-lambda-python/blob/53b1ebdbe74d9187d4e2ecf893a73050c4de9217/setup.py#L33

**Comment by tianchu** [comment]
@piohhmy Thanks, I didn't read your original post throughly, sorry about that! We do update our dependencies regularly. Is this a blocker for you? I believe if you pin the `ddtrace` to a newer version in your own requirements.txt, it would take precedence over the version pinned by `datadog-lambda`.

**Comment by Czechh** [comment]
@piohhmy we've updated `ddtrace` dependency in https://github.com/DataDog/datadog-lambda-python/pull/85

Thank you!
