### ISSUE TITLE
Support for events?

### ISSUE THREAD

**Issue by hawkaa** [DataDog/datadog-lambda-python#97]
I am quite new with datadog, but I am trying to replace Sentry with datadog to report errors/exceptions in my AWS lambdas. As far as I know, you are supposed to use [Datadog Events](https://docs.datadoghq.com/developers/events/) for that. However, it doesn't seem like this project supports posting custom events, only logs, traces, and metrics. Is this right?

I know I can set up monitoring on logs and log levels, but I prefer getting a message on slack on every exception, and not set up a monitor that sets an alarm state if the amount of errors are above 0 for 5 minutes. Sentry does exactly that and gives me the opportunity to resolve, snooze, and assign issues.

Maybe my expectations to datadog and this library are too high, and that I should continue using both datadog and sentry, which would work. Anyway, let me know what you think!

**Comment by agocs** [comment]
Good morning @hawkaa. You're correct about the Datadog lambda libraries only supporting logs, traces, and metrics. I understand what you're trying to do, but I don't think writing directly to the Event stream is the best way to do it. Our Solutions Engineering team (support@datadoghq.com) might be able to help you write all your exceptions to Slack.

**Comment by hawkaa** [comment]
@agocs thank you so much for the reply! As we are customers of Datadog, I should of course have talked with support through the official channels rather than creating an issue here. I will get in touch.

The reason why I posted here, though, is that there are [examples in the Datadog documentation where you can use Dogstatsd or some of the other python packages to send events](https://docs.datadoghq.com/developers/events/dogstatsd/). As far as I know, you don't have access to the dogstatsd interface using `datadog-lambda-python`, thus I was wondering if events were supported at all.

**Comment by tianchu** [comment]
@hawkaa with the launch of [Datadog Lambda extension](https://docs.datadoghq.com/serverless/libraries_integrations/extension/), which is a special edition of the normal Datadog agent, and you might be able to give it a shot.

**Comment by hawkaa** [comment]
> @hawkaa with the launch of [Datadog Lambda extension](https://docs.datadoghq.com/serverless/libraries_integrations/extension/), which is a special edition of the normal Datadog agent, and you might be able to give it a shot.

Thank you!

**Comment by tianchu** [comment]
@hawkaa any luck? BTW, you could also send your events as logs to Datadog and set up a monitor on your special logs to achieve the similar monitoring goal. Will keep the issue open for a while to see if anyone else expressing interests in this feature request.

**Comment by hawkaa** [comment]
> @hawkaa any luck? BTW, you could also send your events as logs to Datadog and set up a monitor on your special logs to achieve the similar monitoring goal. Will keep the issue open for a while to see if anyone else expressing interests in this feature request.

Hi. I am terribly sorry. There has been no time yet to do so as we already got our monitoring set up with Sentry and it works. I would love to test it at one point, but there has not been time yet :(

**Comment by tianchu** [comment]
Closing for the lack of activity and interests from the rest of the community.
